### ISSUE TITLE
Not able to roated PIN PAD numbers 

### ISSUE THREAD

**Issue by scriptchamp** [yannickebongue/jquery-ui-pinpad#1]
I want to display pin pad on JSP page how can I use generateRandomKeys  function to generate random number on pin pad.

**Comment by yannickebongue** [comment]
All you need to do is to set the `keys` option by calling the `$.ui.pinpad.generateRandomKeys()` method.

This can be done when initializing the pin pad or by invoking `option("keys", $.ui.pinpad.generateRandomKeys())` on the pin pad widget at any time after initialization.
